admin_dogs_index:
    path:     /admin/dogs
    defaults: { _controller: "RibercanAdminDogBundle:Dog:index" }
    methods:  GET

admin_dogs_new:
    path:     /admin/dogs/new
    defaults: { _controller: "RibercanAdminDogBundle:Dog:new" }
    methods:  [GET, POST]

admin_dogs_show:
    path:     /admin/dogs/{id}/show
    defaults: { _controller: "RibercanAdminDogBundle:Dog:show" }
    methods:  GET

admin_dogs_edit:
    path:     /admin/dogs/{id}/edit
    defaults: { _controller: "RibercanAdminDogBundle:Dog:edit" }
    methods:  [GET, POST]

admin_dogs_delete:
    path:     /admin/dogs/{id}/delete
    defaults: { _controller: "RibercanAdminDogBundle:Dog:delete" }
    methods:  DELETE

admin_dog_images_index:
    path:     /admin/dogs/{id}/images
    defaults: { _controller: "RibercanAdminDogBundle:DogImage:index" }
    methods:  [GET, POST]

admin_dog_images_mark_as_cover:
    path:     /admin/dogs/{dog_id}/images/{id}
    defaults: { _controller: "RibercanAdminDogBundle:DogImage:markAsCover" }
    methods:  GET
