_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_errors:
      resource: "@TwigBundle/Resources/config/routing/errors.xml"
      prefix:   /_error

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_main:
    resource: routing.yml

_dog:
    resource: "@RibercanDogBundle/Resources/config/routing.yml"
