ribercan_how_to_help:
    resource: "@RibercanHowToHelpBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_app:
    resource: "@RibercanAppBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_dog:
    resource: "@RibercanDogBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_about_us:
    resource: "@RibercanAboutUsBundle/Resources/config/routing.yml"
    prefix:   /about-us

ribercan_admin_app:
    resource: "@RibercanAdminAppBundle/Resources/config/routing.yml"
    prefix:   /admin

ribercan_admin_dog:
    resource: "@RibercanAdminDogBundle/Resources/config/routing.yml"
    prefix:   /admin
