ribercan_frontpage:
    resource: "@RibercanFrontpageBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_dog:
    resource: "@RibercanDogBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_news:
    resource: "@RibercanNewsBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_about_us:
    resource: "@RibercanAboutUsBundle/Resources/config/routing.yml"
    prefix:   /about-us

ribercan_how_to_help:
    resource: "@RibercanHowToHelpBundle/Resources/config/routing.yml"
    prefix:   /how-to-help

ribercan_admin_app:
    resource: "@RibercanAdminAppBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_admin_dog:
    resource: "@RibercanAdminDogBundle/Resources/config/routing.yml"
    prefix:   /
