ribercan_advices:
    resource: "@RibercanAdvicesBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_frontpage:
    resource: "@RibercanFrontpageBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_dog:
    resource: "@RibercanDogBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_news:
    resource: "@RibercanNewsBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_admin_news:
    resource: "@RibercanAdminNewsBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_event:
    resource: "@RibercanEventBundle/Resources/config/routing.yml"
    prefix:   /events

ribercan_admin_event:
    resource: "@RibercanAdminEventBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_about_us:
    resource: "@RibercanAboutUsBundle/Resources/config/routing.yml"
    prefix:   /about-us

ribercan_how_to_help:
    resource: "@RibercanHowToHelpBundle/Resources/config/routing.yml"
    prefix:   /how-to-help

ribercan_admin_app:
    resource: "@RibercanAdminAppBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_admin_dog:
    resource: "@RibercanAdminDogBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_shop:
    resource: "@RibercanShopBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_admin_shop:
    resource: "@RibercanAdminShopBundle/Resources/config/routing.yml"
    prefix:   /
