ribercan_app:
    resource: "@RibercanAppBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_dog:
    resource: "@RibercanDogBundle/Resources/config/routing.yml"
    prefix:   /

ribercan_admin_dog:
    resource: "@RibercanAdminDogBundle/Controller/"
    type:     annotation
    prefix:   /admin

ribercan_admin_news:
    resource: "@RibercanAdminNewsBundle/Controller/"
    type:     annotation
    prefix:   /admin

