<?php

namespace Ribercan\Admin\DogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DogImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogImageRepository extends EntityRepository
{
}
