<?php

namespace Ribercan\Admin\DogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends EntityRepository
{
    public function findUrgentAdoptions()
    {
        return $this->findBy(array('urgent' => true));
    }
}
