ribercan_about_us_homepage:
    path:     /
    defaults: { _controller: RibercanAboutUsBundle:StaticPages:aboutUs }
ribercan_about_us_contacts:
    path:     /contacts
    defaults: { _controller: RibercanAboutUsBundle:StaticPages:contacts }
ribercan_about_us_for_regina:
    path:     /for-regina
    defaults: { _controller: RibercanAboutUsBundle:StaticPages:forRegina }
ribercan_about_us_ribercan_friends:
    path:     /ribercan-friends
    defaults: { _controller: RibercanAboutUsBundle:StaticPages:ribercanFriends }
