<?php

namespace Ribercan\Admin\DogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends EntityRepository
{
}
